### ISSUE TITLE
general query

### ISSUE THREAD

**Issue by mydata** [aa8y/docker-sbt#1]
What is the purpose of the sbt*.sh script in this repo? Is this  only to use as sbt executable , when only the jar file is available? which will be replaced by actual sbt executable in case of 1.x versions?

**Comment by aa8y** [comment]
That's a fairly accurate assessment, with the exception that we need the `sbt*.sh` script for only the 0.12.x versions of SBT. That's why the script itself is names `sbt-0.12.sh`. Starting version 0.13.x this was no longer required.

**Comment by aa8y** [comment]
@mydata Since there has been no other response here in the last 10 days, I am closing this. Feel free to open this if your question has not been answered.
